### ISSUE TITLE
Problem with the calculation of the q matrix after modifying the EventAnalysis code

### ISSUE THREAD

**Issue by mhuia** [professorcode1/Event-Analysis#1]
First of all, I would like to thank the author for their excellent work on the `EventAnalysis` package and for providing the `ES` method.

I have been using this method and made a modification to the calculation of the `q` matrix. In the original code, the `Q` matrix is computed as follows:
```python
Q = np.add(c_i_j, c_i_j.T).astype('float32')
```
This calculation works as expected, and the `Q` matrix produces the correct result. However, to meet my specific needs for calculating the delay matrix, I modified the code to:
```python
q = np.subtract(c_i_j, c_i_j.T).astype('float32')
```
Now, the `Q` matrix is still computed correctly, but the `q` matrix always results in a zero matrix.
In the original code, the `Q` matrix is computed via addition and is symmetric (`Q = Q.T`). However, I expected `c_i_j` to be a non-symmetric matrix, i.e., `c_i_j != c_i_j.T`. Therefore, I expected the calculation of `q = np.subtract(c_i_j, c_i_j.T)` to yield a non-zero matrix, rather than a zero matrix.

The current result suggests that `c_i_j` is symmetric, which leads to the subtraction `c_i_j - c_i_j.T` resulting in a zero matrix.
Why has `c_i_j` become symmetric? I originally assumed that `c_i_j` should be non-symmetric.

**Comment by professorcode1** [comment]
Hey! Thank you for all the kind words! 

I ran the algorithm locally using the Indian Monsoon data you can find in my "bench against coincalc" folder and I only got   ~4.6% of c_i_j values being equal to c_j_i. There's nothing in the code causing your c_i_j's to be symmetric. Your input must have some sort of symmetry in it.
